### ISSUE TITLE
three possible improvements

### ISSUE THREAD

**Issue by krobsp** [gusbrs/postnotes#7]
Hi! First, thank you for the marvelous postnotes package, I am using it a lot (especially the backreference in the postnote marks). There are a few features I wondered if they could be "easily" added : 

1- I would be glad to be able to use multiple series of end notes (therefore, \printpostnotes would print the postnotes sorted by type (and, secondarily, order of appearance). 
2- Also, I asked wondered if it was possible to have a "runin" printpostnotes (that is, with no heading at all, and even no new par). 
3- finally, It would be interesting for the user to have a boolean to test if the current printpostnotes is empty (rather than printing it and getting the warning during compilation). 

I do not know what is easy and what is totally untractable in the previous tracks but I found interesting to ask the package author. 
 
Thanks !

**Comment by gusbrs** [comment]
Hi, @krobsp , I'm glad you are enjoying it. And thanks for the suggestions.

> 1- I would be glad to be able to use multiple series of end notes (therefore, \printpostnotes would print the postnotes sorted by type (and, secondarily, order of appearance).

This is one thing I thought about providing, but eventually didn't (at least so far). For one thing, it is some work, though not impossible either. It would also make the infrastructure more complex, which is something to ponder.

More importantly, I'm not sure the use case for multiple series of end notes is that pressing. Sure, there are critical editions which need it. But someone doing one of those will probably be using `reledmac`, which already provides such facilities. Other than that, I'm not sure how needed this is. The fact that neither `endnotes` or `enotez` provide this functionality suggests the use case is, at most, a niche one. Also, technically, it is possible to use `postnotes` alongside either `endnotes` or `enotez`, so you can get away with different series as things stand. True, not the same functionality, thus not ideal. Still a pretty decent alternative for a special use case.

Could you elaborate on the use case(s) you have in mind in making such suggestion?

> 2- Also, I asked wondered if it was possible to have a "runin" printpostnotes (that is, with no heading at all, and even no new par).

I'm not sure I understand but, as far as I do, this is already possible. Just choose `listenv=none` and set an empty `postprintnote`:

```tex
\documentclass{book}

\usepackage{postnotes}
\postnotesetup{
  listenv=none,
  postprintnote=,
}

\usepackage{lipsum}
\usepackage{hyperref}

\begin{document}

\tableofcontents{}

\chapter{Chapter 1}

\lipsum[1-2]\postnote{\lipsum[3]}\par
\lipsum[1-2]\postnote{\lipsum[3]}\par
\lipsum[1-2]\postnote{\lipsum[3]}\par

\chapter{Chapter 2}

\lipsum[1-2]\postnote{\lipsum[3]}\par
\lipsum[1-2]\postnote{\lipsum[3]}\par
\lipsum[1-2]\postnote{\lipsum[3]}\par

\printpostnotes

\end{document}
```

> 3- finally, It would be interesting for the user to have a boolean to test if the current printpostnotes is empty (rather than printing it and getting the warning during compilation).

What do you mean here? You'd like to be able do "disable the warning"? Is that it?

If that's what you meant, it'd be easy to implement, but I don't think it is a good idea. It is just a warning, not an error. It is the same behavior as `biblatex`'s `\printbibliography`, which sounds like a good standard practice to follow.

**Comment by krobsp** [comment]
Thanks for the (super-fast) answer !
1- As a case, I thought about a pedagogical document with different "kinds" of postnotes according to the "skill" of the postnote:` Apostnotes` for very fundamental remarks, `Bpostnotes` for advanced students, `Cpostnotes` for hard exercises and so on...

2- Perfect, this is exactly what I meant, thanks !

3- I did not mean to purely disable the warning. Let me elaborate a little bit : I am using very frequently using `\printpostnotes` in my document (so that, by the way, I am not sure that `endnotes` and `enotez` packages are made for that.), say, after each subsection. 
But, it happens that there is nothing to print. I wanted to display, in such a case, something in the document itself. So, it would be useful to have a boolean, say \postnotesareempty, so that I can write something like \if\postnotesarempty{There is no postnote here. I had no interesting observation to make}\else{\printpostnotes}

**Comment by gusbrs** [comment]
> 1- As a case, I thought about a pedagogical document with different "kinds" of postnotes according to the "skill" of the postnote:` Apostnotes` for very fundamental remarks, `Bpostnotes` for advanced students, `Cpostnotes` for hard exercises and so on...

I see. Well, for this kind of use case, I'd suggest adding some marker, at the start of the note, or in the margin.

But I get what you'd like to do. Still, I'm not convinced the use case justifies the added complexity which would be required for this to work. I'll keep the suggestion in mind, but I won't make you any promises in this regard.

> 3- I did not mean to purely disable the warning. Let me elaborate a little bit : I am using very frequently using `\printpostnotes` in my document (so that, by the way, I am not sure that `endnotes` and `enotez` packages are made for that.), say, after each subsection.
> But, it happens that there is nothing to print. I wanted to display, in such a case, something in the document itself. So, it would be useful to have a boolean, say \postnotesareempty, so that I can write something like \if\postnotesarempty{There is no postnote here. I had no interesting observation to make}\else{\printpostnotes}

For this situation, I'd suggest a simpler approach: disable the notes heading and add it manually. For example:

```tex
\documentclass{book}

\usepackage{postnotes}
\postnotesetup{heading=}

\usepackage{lipsum}
\usepackage{hyperref}

\begin{document}

\tableofcontents{}

\chapter{Chapter 1}

\lipsum[1-2]\postnote{\lipsum[3]}\par
\lipsum[1-2]\postnote{\lipsum[3]}\par
\lipsum[1-2]\postnote{\lipsum[3]}\par

\section*{Notes foo}
\printpostnotes

\chapter{Chapter 2}

\section*{Notes bar}
\printpostnotes

\end{document}
```

I know this is not the same thing since the heading is printed unconditionally. But hopefully it is sufficient for what you need.

If you really, really need a conditional test, you could build one base on the main counter of the notes (called, as you'd expect, `postnotes`). Just test if the counter hasn't changed since the last call with something like:

```tex
\documentclass{book}

\usepackage{postnotes}
\postnotesetup{heading=}

\ExplSyntaxOn
\newcounter{mysavedpostnote}
\NewDocumentCommand{\myemptyposnotes}{m}{
  \int_compare:nNnT
    { \int_use:c { c@postnote } }
    =
    { \int_use:c { c@mysavedpostnote } }
    { #1 }
  \setcounter{mysavedpostnote}{\value{postnote}}
}
\ExplSyntaxOff


\usepackage{lipsum}
\usepackage{hyperref}

\begin{document}

\tableofcontents{}

\chapter{Chapter 1}

\lipsum[1-2]\postnote{\lipsum[3]}\par
\lipsum[1-2]\postnote{\lipsum[3]}\par
\lipsum[1-2]\postnote{\lipsum[3]}\par

\section*{Notes foo}
\myemptyposnotes{No notes on this part}
\printpostnotes

\chapter{Chapter 2}

\section*{Notes bar}
\myemptyposnotes{No notes on this part either}
\printpostnotes

\end{document}
```

All in all, I don't think there's enough to justify exposing a user interface for this purpose. But, of course, it is possible to perform the test rigorously using the package's internals, if you know your way around the code. Naturally, formally, "it is not recommended nor supported". ;-)

Btw, yes you can use the equivalent of `\printpostnotes` provided by `endnotes` or `enotez` multiple times, this is just standard behavior of end notes packages.

**Comment by krobsp** [comment]
wonderful; thanks a lot !

**Comment by gusbrs** [comment]
Thanks again for the suggestions. Cheers!
